package io.etwallet.etpay.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class BtcUnspendTx {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column btc_unspend_tx.id
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column btc_unspend_tx.address
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column btc_unspend_tx.txid
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	private String txid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column btc_unspend_tx.output_index
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	private Integer outputIndex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column btc_unspend_tx.script
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	private String script;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column btc_unspend_tx.qty
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	private BigDecimal qty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column btc_unspend_tx.height
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	private Integer height;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column btc_unspend_tx.createtime
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column btc_unspend_tx.updatetime
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	private Date updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column btc_unspend_tx.is_used
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	private Integer isUsed;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column btc_unspend_tx.id
	 * @return  the value of btc_unspend_tx.id
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column btc_unspend_tx.id
	 * @param id  the value for btc_unspend_tx.id
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column btc_unspend_tx.address
	 * @return  the value of btc_unspend_tx.address
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column btc_unspend_tx.address
	 * @param address  the value for btc_unspend_tx.address
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column btc_unspend_tx.txid
	 * @return  the value of btc_unspend_tx.txid
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public String getTxid() {
		return txid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column btc_unspend_tx.txid
	 * @param txid  the value for btc_unspend_tx.txid
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public void setTxid(String txid) {
		this.txid = txid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column btc_unspend_tx.output_index
	 * @return  the value of btc_unspend_tx.output_index
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public Integer getOutputIndex() {
		return outputIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column btc_unspend_tx.output_index
	 * @param outputIndex  the value for btc_unspend_tx.output_index
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public void setOutputIndex(Integer outputIndex) {
		this.outputIndex = outputIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column btc_unspend_tx.script
	 * @return  the value of btc_unspend_tx.script
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public String getScript() {
		return script;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column btc_unspend_tx.script
	 * @param script  the value for btc_unspend_tx.script
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public void setScript(String script) {
		this.script = script;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column btc_unspend_tx.qty
	 * @return  the value of btc_unspend_tx.qty
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public BigDecimal getQty() {
		return qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column btc_unspend_tx.qty
	 * @param qty  the value for btc_unspend_tx.qty
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column btc_unspend_tx.height
	 * @return  the value of btc_unspend_tx.height
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public Integer getHeight() {
		return height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column btc_unspend_tx.height
	 * @param height  the value for btc_unspend_tx.height
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public void setHeight(Integer height) {
		this.height = height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column btc_unspend_tx.createtime
	 * @return  the value of btc_unspend_tx.createtime
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column btc_unspend_tx.createtime
	 * @param createtime  the value for btc_unspend_tx.createtime
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column btc_unspend_tx.updatetime
	 * @return  the value of btc_unspend_tx.updatetime
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column btc_unspend_tx.updatetime
	 * @param updatetime  the value for btc_unspend_tx.updatetime
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column btc_unspend_tx.is_used
	 * @return  the value of btc_unspend_tx.is_used
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public Integer getIsUsed() {
		return isUsed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column btc_unspend_tx.is_used
	 * @param isUsed  the value for btc_unspend_tx.is_used
	 * @mbg.generated  Thu Jul 11 19:37:11 CST 2019
	 */
	public void setIsUsed(Integer isUsed) {
		this.isUsed = isUsed;
	}
}