package com.morningpay.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class NoticeObj implements Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.id
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.txId
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private String txid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.type
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.address
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.symbol
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private String symbol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.direction
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private String direction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.qty
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private BigDecimal qty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.blockhash
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private String blockhash;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.block_hight
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private Long blockHight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.cur_block_hight
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private Long curBlockHight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.contract
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private String contract;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.serial_number
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private String serialNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.userId
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private Long userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.first_notice_counter
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private Long firstNoticeCounter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.second_notice_counter
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private Long secondNoticeCounter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.uniquekey
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private String uniquekey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.memo
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private String memo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.coin_type
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private String coinType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.createtime
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice_obj.updatetime
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	private Date updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.id
	 * @return  the value of notice_obj.id
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.id
	 * @param id  the value for notice_obj.id
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.txId
	 * @return  the value of notice_obj.txId
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public String getTxid() {
		return txid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.txId
	 * @param txid  the value for notice_obj.txId
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setTxid(String txid) {
		this.txid = txid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.type
	 * @return  the value of notice_obj.type
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.type
	 * @param type  the value for notice_obj.type
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.address
	 * @return  the value of notice_obj.address
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.address
	 * @param address  the value for notice_obj.address
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.symbol
	 * @return  the value of notice_obj.symbol
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public String getSymbol() {
		return symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.symbol
	 * @param symbol  the value for notice_obj.symbol
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.direction
	 * @return  the value of notice_obj.direction
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public String getDirection() {
		return direction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.direction
	 * @param direction  the value for notice_obj.direction
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setDirection(String direction) {
		this.direction = direction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.qty
	 * @return  the value of notice_obj.qty
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public BigDecimal getQty() {
		return qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.qty
	 * @param qty  the value for notice_obj.qty
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.blockhash
	 * @return  the value of notice_obj.blockhash
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public String getBlockhash() {
		return blockhash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.blockhash
	 * @param blockhash  the value for notice_obj.blockhash
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setBlockhash(String blockhash) {
		this.blockhash = blockhash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.block_hight
	 * @return  the value of notice_obj.block_hight
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public Long getBlockHight() {
		return blockHight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.block_hight
	 * @param blockHight  the value for notice_obj.block_hight
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setBlockHight(Long blockHight) {
		this.blockHight = blockHight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.cur_block_hight
	 * @return  the value of notice_obj.cur_block_hight
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public Long getCurBlockHight() {
		return curBlockHight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.cur_block_hight
	 * @param curBlockHight  the value for notice_obj.cur_block_hight
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setCurBlockHight(Long curBlockHight) {
		this.curBlockHight = curBlockHight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.contract
	 * @return  the value of notice_obj.contract
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public String getContract() {
		return contract;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.contract
	 * @param contract  the value for notice_obj.contract
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setContract(String contract) {
		this.contract = contract;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.serial_number
	 * @return  the value of notice_obj.serial_number
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public String getSerialNumber() {
		return serialNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.serial_number
	 * @param serialNumber  the value for notice_obj.serial_number
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.userId
	 * @return  the value of notice_obj.userId
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.userId
	 * @param userid  the value for notice_obj.userId
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.first_notice_counter
	 * @return  the value of notice_obj.first_notice_counter
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public Long getFirstNoticeCounter() {
		return firstNoticeCounter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.first_notice_counter
	 * @param firstNoticeCounter  the value for notice_obj.first_notice_counter
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setFirstNoticeCounter(Long firstNoticeCounter) {
		this.firstNoticeCounter = firstNoticeCounter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.second_notice_counter
	 * @return  the value of notice_obj.second_notice_counter
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public Long getSecondNoticeCounter() {
		return secondNoticeCounter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.second_notice_counter
	 * @param secondNoticeCounter  the value for notice_obj.second_notice_counter
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setSecondNoticeCounter(Long secondNoticeCounter) {
		this.secondNoticeCounter = secondNoticeCounter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.uniquekey
	 * @return  the value of notice_obj.uniquekey
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public String getUniquekey() {
		return uniquekey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.uniquekey
	 * @param uniquekey  the value for notice_obj.uniquekey
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setUniquekey(String uniquekey) {
		this.uniquekey = uniquekey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.memo
	 * @return  the value of notice_obj.memo
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.memo
	 * @param memo  the value for notice_obj.memo
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.coin_type
	 * @return  the value of notice_obj.coin_type
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public String getCoinType() {
		return coinType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.coin_type
	 * @param coinType  the value for notice_obj.coin_type
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setCoinType(String coinType) {
		this.coinType = coinType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.createtime
	 * @return  the value of notice_obj.createtime
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.createtime
	 * @param createtime  the value for notice_obj.createtime
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice_obj.updatetime
	 * @return  the value of notice_obj.updatetime
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice_obj.updatetime
	 * @param updatetime  the value for notice_obj.updatetime
	 * @mbg.generated  Tue Jun 11 22:06:16 CST 2019
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
}